"""Sensitivity / robustness analysis for the MTI composite.

Standalone — NOT part of the pipeline hot path. On a fixed event fixture it
perturbs the modelling choices that have no empirical anchor (category weights,
country strategic weights, recency half-life, and the saturation constants) one
at a time, and reports how the composite and the country ranking move. This is
the uncertainty/sensitivity step recommended for any composite indicator
(OECD/JRC 2008; Saisana, Saltelli & Tarantola 2005).

Run:  python -m scripts.sensitivity   ->  writes docs/methodology_sensitivity.md
"""
from __future__ import annotations

import copy
import os

from pipeline import config as cfgmod, score as scoremod
from pipeline.util import ROOT, utcnow


def _ranking(result):
    return [n for n, _ in sorted(result["countries"].items(),
            key=lambda kv: kv[1]["index"], reverse=True)]


def _composite_with(cfg, events, weight_scale=None, country_weight_scale=None,
                    half_life=None, sat_scale=None, sat_gain=None):
    cfg2 = copy.deepcopy(cfg)
    sc = cfg2.settings.setdefault("score", {})
    if half_life is not None:
        sc["recency_half_life_h"] = half_life
    if sat_scale is not None:
        sc["saturation_scale"] = sat_scale
    if sat_gain is not None:
        sc["saturation_gain"] = sat_gain
    if country_weight_scale is not None:
        for c in cfg2.countries:
            c.weight = c.weight * country_weight_scale
    evs = copy.deepcopy(events)
    if weight_scale is not None:
        for e in evs:
            e["weight"] = float(e.get("weight", 0.0)) * weight_scale
    return scoremod.score(evs, cfg2)


_GRID = [
    ("category weights -20%", dict(weight_scale=0.8)),
    ("category weights +20%", dict(weight_scale=1.2)),
    ("country weights -20%", dict(country_weight_scale=0.8)),
    ("country weights +20%", dict(country_weight_scale=1.2)),
    ("half-life 9h (faster decay)", dict(half_life=9.0)),
    ("half-life 36h (slower decay)", dict(half_life=36.0)),
    ("saturation gain 1.0", dict(sat_gain=1.0)),
    ("saturation gain 1.5", dict(sat_gain=1.5)),
    ("saturation scale 4.0", dict(sat_scale=4.0)),
    ("saturation scale 6.0", dict(sat_scale=6.0)),
]


def run_sensitivity(cfg, events):
    """Return baseline + one-at-a-time perturbation results and the composite range."""
    base = scoremod.score(copy.deepcopy(events), copy.deepcopy(cfg))
    base_comp = base["composite"]
    base_rank = _ranking(base)
    comps = [base_comp]
    scenarios = []
    for name, kw in _GRID:
        r = _composite_with(cfg, events, **kw)
        rank = _ranking(r)
        scenarios.append({
            "name": name,
            "composite": r["composite"],
            "delta": round(r["composite"] - base_comp, 3),
            "top3_changed": set(rank[:3]) != set(base_rank[:3]),
        })
        comps.append(r["composite"])
    return {"baseline": {"composite": base_comp, "ranking": base_rank},
            "scenarios": scenarios,
            "composite_range": [min(comps), max(comps)]}


def _fixture(cfg):
    """A small, deterministic multi-country / multi-category event set."""
    now = utcnow()
    cw = cfg.cat_weight

    def ev(country, cat, src):
        return {"country": country, "category": cat, "weight": cw.get(cat, 0.0),
                "credibility": 1.0, "source": src, "title": f"{country} {cat}",
                "link": "", "published": now, "lang": "en", "corroboration": 2}

    return [
        ev("Iran", "military_conflict", "Reuters"),
        ev("Iran", "diplomatic_tensions", "AP"),
        ev("Israel", "military_conflict", "BBC"),
        ev("Israel", "border_security", "Reuters"),
        ev("Egypt", "political_instability", "AP"),
        ev("Syria", "humanitarian_crisis", "Reuters"),
        ev("Turkey", "diplomatic_tensions", "BBC"),
    ]


def to_markdown(res):
    r = res["baseline"]
    lines = [
        "# MTI methodology — sensitivity analysis",
        "",
        "_Generated by `python -m scripts.sensitivity` on a fixed event fixture. "
        "One-at-a-time perturbations of the unanchored modelling choices "
        "(OECD/JRC 2008; Saisana, Saltelli & Tarantola 2005). Not part of the pipeline._",
        "",
        f"- **Baseline composite:** {r['composite']:.2f}",
        f"- **Composite range across perturbations:** "
        f"{res['composite_range'][0]:.2f} – {res['composite_range'][1]:.2f}",
        f"- **Baseline top-3:** {', '.join(r['ranking'][:3])}",
        "",
        "| Perturbation | Composite | Δ | Top-3 changed |",
        "|---|---:|---:|:---:|",
    ]
    for s in res["scenarios"]:
        lines.append(f"| {s['name']} | {s['composite']:.2f} | {s['delta']:+.2f} | "
                     f"{'yes' if s['top3_changed'] else 'no'} |")
    return "\n".join(lines) + "\n"


def main():
    cfg = cfgmod.load()
    res = run_sensitivity(cfg, _fixture(cfg))
    out = os.path.join(ROOT, "docs", "methodology_sensitivity.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(to_markdown(res))
    b = res["baseline"]
    lo, hi = res["composite_range"]
    print(f"wrote {out}")
    print(f"baseline composite {b['composite']:.2f}; range {lo:.2f}-{hi:.2f} "
          f"across {len(res['scenarios'])} perturbations; top-3 {', '.join(b['ranking'][:3])}")


if __name__ == "__main__":
    main()
